### PR TITLE
updates change application/csv+text to text/csv

### LINKED ISSUE #1: Add time out specification in swaggerHub definition of the API
As a user of the API, I want to have an homogeneous way of getting error or status for long requests or requests longer than supported by a synchronous web API.

### LINKED ISSUE #2: Add list of available fields in response format
As a user, I want to know which fields I can request to the API.

### PR DESCRIPTION
**Pull request by al-niessner**
## 🗒️ Summary
Quick typo fix

## ⚙️ Test Data and/or Report
One of the following should be included here:
* Reference to regression test included in code (preferred wherever reasonable)
* Attach test data here + outputs of tests

### CODE REVIEW

**Comment by al-niessner** [comment]
@tloubrieu-jpl @jordanpadams 

Can I get this merged to main and new maven artifact built so that I can close out the other pull request that is awaiting this change: https://github.com/NASA-PDS/registry-api-service/pull/90

**Comment by al-niessner** [comment]
@tloubrieu-jpl @jordanpadams 

I fixed all the easy stuff and moving to the fields problem now. I prefer to fix them all here rather than pushing broken code to the main branch.

**Comment by al-niessner** [comment]
@tloubrieu-jpl @jordanpadams 

Little help please as in some reading material or hint or something to give me traction. When I use this curl:

```
curl --location --request GET 'http://localhost:8080/products' --header 'Accept: application/csv'
```

It generates this at the server:

```
2021-12-08 21:56:19.545 DEBUG 53 --- [0.3-8080-exec-1] o.a.coyote.http11.Http11InputBuffer      : Received [GET /products HTTP/1.1
Host: localhost:8080
User-Agent: curl/7.68.0
Accept: application/csv

]
2021-12-08 21:56:19.553 DEBUG 53 --- [0.3-8080-exec-1] org.apache.tomcat.util.http.Parameters   : Set query string encoding to UTF-8
2021-12-08 21:56:19.555 DEBUG 53 --- [0.3-8080-exec-1] o.a.c.authenticator.AuthenticatorBase    : Security checking request GET /products
2021-12-08 21:56:19.555 DEBUG 53 --- [0.3-8080-exec-1] org.apache.catalina.realm.RealmBase      :   No applicable constraints defined
2021-12-08 21:56:19.557 DEBUG 53 --- [0.3-8080-exec-1] o.a.c.a.jaspic.AuthConfigFactoryImpl     : Loading persistent provider registrations from [/tmp/tomcat.5901048604994473389.8080/conf/jaspic-providers.xml]
2021-12-08 21:56:19.557 DEBUG 53 --- [0.3-8080-exec-1] o.a.c.authenticator.AuthenticatorBase    : Not subject to any constraint
2021-12-08 21:56:19.559  INFO 53 --- [0.3-8080-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2021-12-08 21:56:19.559  INFO 53 --- [0.3-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2021-12-08 21:56:19.559 DEBUG 53 --- [0.3-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Detected StandardServletMultipartResolver
2021-12-08 21:56:19.563 DEBUG 53 --- [0.3-8080-exec-1] o.s.web.servlet.DispatcherServlet        : enableLoggingRequestDetails='false': request parameters and headers will be masked to prevent unsafe logging of potentially sensitive data
2021-12-08 21:56:19.563  INFO 53 --- [0.3-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 4 ms
2021-12-08 21:56:19.566 DEBUG 53 --- [0.3-8080-exec-1] org.apache.tomcat.util.http.Parameters   : Set encoding to UTF-8
2021-12-08 21:56:19.566 DEBUG 53 --- [0.3-8080-exec-1] o.s.web.servlet.DispatcherServlet        : GET "/products", parameters={}
2021-12-08 21:56:19.567 DEBUG 53 --- [0.3-8080-exec-1] pertySourcedRequestMappingHandlerMapping : looking up handler for path: /products
2021-12-08 21:56:19.569 DEBUG 53 --- [0.3-8080-exec-1] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped to gov.nasa.pds.api.engineering.controllers.MyProductsApiController#products(Integer, Integer, String, String, List, List, Boolean)
2021-12-08 21:56:19.577 DEBUG 53 --- [0.3-8080-exec-1] g.n.p.a.e.c.MyProductsApiBareController  : accept value is application/csv
2021-12-08 21:56:19.577 DEBUG 53 --- [0.3-8080-exec-1] g.n.p.a.e.c.MyProductsApiBareController  : contextPath is: /
2021-12-08 21:56:19.577 DEBUG 53 --- [0.3-8080-exec-1] g.n.p.a.e.c.MyProductsApiBareController  : baseUrl is http://localhost:8080/
```

I can see that the /products endpoint translates to the correct function

```
gov.nasa.pds.api.engineering.controllers.MyProductsApiController#products(Integer,Integer, String, String, List, List, Boolean)
````

When all I do is change the accept and use this curl:

```
curl --location --request GET 'http://localhost:8080/products' --header 'Accept: text/csv'
```

It generates this from the server:

```
2021-12-08 21:56:26.431 DEBUG 53 --- [0.3-8080-exec-2] o.a.coyote.http11.Http11InputBuffer      : Received [GET /products HTTP/1.1
Host: localhost:8080
User-Agent: curl/7.68.0
Accept: text/csv

]
2021-12-08 21:56:26.431 DEBUG 53 --- [0.3-8080-exec-2] o.a.c.authenticator.AuthenticatorBase    : Security checking request GET /products
2021-12-08 21:56:26.431 DEBUG 53 --- [0.3-8080-exec-2] org.apache.catalina.realm.RealmBase      :   No applicable constraints defined
2021-12-08 21:56:26.431 DEBUG 53 --- [0.3-8080-exec-2] o.a.c.authenticator.AuthenticatorBase    : Not subject to any constraint
2021-12-08 21:56:26.431 DEBUG 53 --- [0.3-8080-exec-2] org.apache.tomcat.util.http.Parameters   : Set encoding to UTF-8
2021-12-08 21:56:26.432 DEBUG 53 --- [0.3-8080-exec-2] o.s.web.servlet.DispatcherServlet        : GET "/products", parameters={}
2021-12-08 21:56:26.432 DEBUG 53 --- [0.3-8080-exec-2] pertySourcedRequestMappingHandlerMapping : looking up handler for path: /products
2021-12-08 21:56:26.434  WARN 53 --- [0.3-8080-exec-2] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.web.HttpMediaTypeNotAcceptableException: Could not find acceptable representation]
2021-12-08 21:56:26.434 DEBUG 53 --- [0.3-8080-exec-2] o.s.web.servlet.DispatcherServlet        : Completed 406 NOT_ACCEPTABLE
2021-12-08 21:56:26.434 DEBUG 53 --- [0.3-8080-exec-2] o.a.c.c.C.[Tomcat].[localhost]           : Processing ErrorPage[errorCode=0, location=/error]
2021-12-08 21:56:26.436 DEBUG 53 --- [0.3-8080-exec-2] o.s.web.servlet.DispatcherServlet        : "ERROR" dispatch for GET "/error", parameters={}
2021-12-08 21:56:26.436 DEBUG 53 --- [0.3-8080-exec-2] pertySourcedRequestMappingHandlerMapping : looking up handler for path: /error
2021-12-08 21:56:26.436 DEBUG 53 --- [0.3-8080-exec-2] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped to org.springframework.boot.autoconfigure.web.servlet.error.BasicErrorController#error(HttpServletRequest)
2021-12-08 21:56:26.443 DEBUG 53 --- [0.3-8080-exec-2] .m.m.a.ExceptionHandlerExceptionResolver : Using @ExceptionHandler org.springframework.boot.autoconfigure.web.servlet.error.BasicErrorController#mediaTypeNotAcceptable(HttpServletRequest)
2021-12-08 21:56:26.444 DEBUG 53 --- [0.3-8080-exec-2] o.s.w.s.m.m.a.HttpEntityMethodProcessor  : No match for [text/csv], supported: [application/json]
```

Where it does not map to the correct function:

```
2021-12-08 21:56:26.432 DEBUG 53 --- [0.3-8080-exec-2] pertySourcedRequestMappingHandlerMapping : looking up handler for path: /products
2021-12-08 21:56:26.434  WARN 53 --- [0.3-8080-exec-2] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.web.HttpMediaTypeNotAcceptableException: Could not find acceptable representation]
```

Now this is where it gets weird. I added application/csv without having to change any server mappings other than ones that I wrote. It seems like spring might be okay with application/* but not text/*. Does this ring any bells with you or do you know any reading I should look at? I just find it odd that all of the application stuff just works while the text stuff is not mapping to our code. However I cannot find any helpful google terms that give me traction and digging down into the code is not helping either.

**Comment by jordanpadams** [comment]
@al-niessner very odd. not sure what is going on there. after a quick google I am just being redirected to tutorials for enabling a CSV response using opencsv, but nothing in particular about not being able to handle `text/csv`

**Comment by al-niessner** [comment]
Yes, same. Trying to tie it back into spring since it looks like it holds
the map. But map from where and with what exactly.

**Comment by al-niessner** [comment]
@tloubrieu-jpl @jordanpadams 

**expletives deleted** maven! It is not listening to me and overwriting my changes with whatever is at sonatype. I cannot stand how maven works but is why things are not working for me right now. It work just fine if this pull request were merged to main.

**Comment by al-niessner** [comment]
@tloubrieu-jpl @jordanpadams 

Now text/csv works. In fact, it all requested add-ons work. Going back to other pull request to find out where I broke fields.

**Review by tloubrieu-jpl — APPROVED** [review]
ok, thanks @al-niessner

**Review by tloubrieu-jpl — APPROVED** [review]

**Pull request merged**
